### ISSUE TITLE
Multi-monitor Game Mirroring & Mirroring Performance

### ISSUE THREAD

**Issue by eedwardsdisco** [TeamAntumbra/wintumbra#19]
0.2.7.1
Windows 8.1
GTX 670 SLI
Dual Monitor (1440p \ 1080p)
Using 2 Glows

Enabling Glow using methods other than 'Game' creates a significant 'stutter' in responsiveness of applications and moving windows around. It seems as the engine samples the screen it creates latency.

Game mode still has some latency but it's severely minimized compared to other modes (e.g. Augment).

I also notice some really distinct and strong coil whine coming from my mobo (not sure which component yet) once I enable either Game mode (whines in a pulsing manner) or the HSV \ Color Pattern modes (whines constantly). Haven't noticed this from any other components, and tried different USB ports. I suspect may be related to frequency that device is pulling current at. Will attempt to isolate.

**Comment by DavisFoster** [comment]
Hardware engineer here - can't speak to the software bugs, but I might be able to shed some light on the audible PSU noise.  Typically coil whine is caused by magnetostriction, where the physical size of the inductor core material is changing as the fields through it collapse.  Current draw in the audible range (60hz to 18khz, give or take) is the culprit here - well below the frequency that our gate-drive PWM is operating at (Mhz range).  What's more likely is that your motherboard has a DC-DC switching regulator onboard that powers the 5v USB rail, which is switching somewhere in the 8khz to 20khz range - and adding a high-current load (like Glow) causes the inductor to resonate enough to produce audible whine. 

If this persists across all your USB ports and is sufficiently annoying, you might be able to resolve it by placing a reasonably sized (~100uF-300uF) electrolytic capacitor across the 5v USB rail on the Antumbra cable.  If you're interested, I could probably hack together a quick fix for you.

**Comment by walshie4** [comment]
This is partially caused because Windows 8's GDI+ performance is lower than that of 7.  However it is also partially caused because right now the capture processes are working totally independently.  We will be releasing an update soon which will optimize this process and hopefully resolve your issues.

**Comment by eedwardsdisco** [comment]
@DavisFoster Thanks for your comment regarding the DC-DC converter. I wouldn't doubt that is the issue. I also tried my USB3 ports since those tend to go through a different controller, and USB3 has more headroom for power delivery, but for some reason the Glow's were not recognized when I used those ports. I have a soldering lab that I'll be setting up again in a month or two, if you can provide specs for the cable mod I would be interested in attempting it once I can. Thanks!

@walshie4 Thanks for your comment - after further review I noticed that the DX screen capture only seems to work on the first monitor, and the Direct3D one doesn't seem to work at all (will bind to process, but won't activate, and attempting to bind again fails as process is already hooked...), so I'm unfortunately limited to using my glows only when watching a video and only when I plan on doing nothing else on the system. I look forward to any further performance updates.

**Comment by walshie4** [comment]
@eedwardsdisco I'll be adding multi-monitor game support after the capture efficiency update.

As for the DirectX extension you're talking about, it has been replaced with the SlimDX one that 'Game Mode' triggers.  We may eventually go back to the injection based one however it is simply way too unstable to use currently.

**Edit:** After further investigation it seems multi-monitor game support is not as simple as I'd hoped.  However it is being worked on and will be available shortly.

**Comment by eedwardsdisco** [comment]
@walshie4 Hi Adam, any updates on this issue? I haven't seen any new commits for a few weeks. Thanks.

**Comment by walshie4** [comment]
Still working on it don't worry.  :) I just haven't pushed to master in a while.  Should be wrapping up soon though!

**Comment by eedwardsdisco** [comment]
Hey @walshie4 any updates on 'soon'? It's been four weeks :)

**Comment by walshie4** [comment]
@eedwardsdisco All of the major codebase structural changes have been completed and a good deal of improvements have been implemented. I'll be posting a snapshot in a few hours for those who have been waiting so patiently to try out and give some feedback.

**Comment by walshie4** [comment]
@eedwardsdisco Great news! The new release (v1.0.0) is almost complete, try it out [here](https://www.reddit.com/r/antumbraglow/comments/3jrw76/v100_prerelease_testing/).  Should be much more efficient and faster. :zap: :runner:  :zap:
