### ISSUE TITLE
Mirror and Argument Buttons Cause Audio Static

### ISSUE THREAD

**Issue by xDeeKay** [TeamAntumbra/wintumbra#33]
Hello, it looks like there hasn't been much activity here until now, so I hope this reaches somebody.

I've just built a new computer with a fresh Windows 10 install, audio drivers, Glow, etc. It's probably important to note that I use a Focusrite Scarlett Solo first gen audio interface and the drivers associated with it.

My issue occurs when I click on either the "Mirror" or "Argument" buttons to simulate the colours on my screen, my audio will become crackly and the ends of sounds will reverb with static. Only when I close the program entirely or go to the "Manual" tab and select a colour does the static disappear.

Decreasing the brightness and capture rate had no effect on this.
Increasing/decreasing my audio sample rate and buffer size also had no effect on this.
Downgrading to an older Focusrite Scarlett Solo driver had no effect.

After 6 years of using this amazing device I would hate to lose this functionality, and any help would be greatly appreciated.
[wintumbra.log](https://github.com/TeamAntumbra/wintumbra/files/5610205/wintumbra.log)

**Comment by walshie4** [comment]
Still looking around for more info on this, but found two links you may be interested in looking more into:
* https://obsproject.com/forum/threads/distortion-with-focusrite-scarlett-audio-interface.61400/
* https://www.gearslutz.com/board/geekslutz-forum/975639-focusrite-scarlett-solo-static-noise.html

Mirror and Augment use graphics processing to do their jobs so I'd guess that is where the issue is coming from.  Will follow up if I find anything else promising or can reproduce on my end.  Also where can I download the audio software you were referencing?

**Comment by xDeeKay** [comment]
Hey walshie, thanks for looking into this for me.

In the time since I posted this, the problem appears to have resolved itself for whatever reason.
The part you mentioned about graphics processing has me thinking it was as simple as a driver update on the GPU end.

Closing the ticket anyway, cheers.
